# .streamlit/secrets.toml
db_host = "ep-shiny-flower-a9mbzik1-pooler.gwc.azure.neon.tech"
db_name = "neondb"
db_user = "neondb_owner"
db_password = "npg_qy8lObmrY7pZ"
db_port = "5432"
db_sslmode = "require"